[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
addopts = --nomigrations --disable-warnings
markers =
    concurrency: marks tests as testing concurrency (deselect with '-m "not concurrency"')
