# Generated by Django 6.1 on 2026-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_file_message_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
