# Generated by Django 6.1 on 2026-09-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_file_alter_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
