# Generated by Django 6.0.7 on 2026-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_codesequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
