# Generated by Django 5.0.6 on 2026-07-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_id_alter_codesequence_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Transaction', 'verbose_name_plural': 'Inventory Transactions'},
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'استلام'), ('OUT', 'صرف'), ('ADJUST', 'جرد')], max_length=10),
        ),
    ]
