# Generated by Django 5.0.6 on 2026-07-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_activitylog_remove_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.CharField(default='Activity', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('ADD', 'إضافة'), ('EDIT', 'تعديل'), ('DELETE', 'حذف'), ('IN', 'استلام'), ('OUT', 'صرف'), ('ADJUST', 'جرد')], max_length=20),
        ),
    ]
