# Generated by Django 5.0.6 on 2026-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_activitylog_description_activitylog_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
