# Generated by Django 5.0.6 on 2026-07-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_activitylog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
