# Generated by Django 6.1 on 2026-09-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_activitylog_user_inventorytransaction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجهة')),
                ('partner_type', models.CharField(choices=[('SUPPLIER', 'مورد'), ('CLIENT', 'عميل / جهة صرف'), ('OTHER', 'جهة أخرى')], default='CLIENT', max_length=20, verbose_name='نوع الجهة')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='بيانات التواصل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المخزن')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='الموقع/العنوان')),
                ('manager', models.CharField(blank=True, max_length=150, null=True, verbose_name='أمين المخزن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر وقت الحركة'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر الشراء/التكلفة'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البيع'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partner', verbose_name='الجهة (المورد / العميل)'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
