# Generated by Django 6.1 on 2026-09-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_populate_initial_warehouse_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.warehouse', verbose_name='المخزن'),
        ),
    ]
