# Generated by Django 6.1 on 2026-09-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_inventorytransaction_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
    ]
