# Generated by Django 6.1 on 2026-09-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_product_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
