# Generated by Django 6.1 on 2026-09-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesequence',
            name='last_number',
        ),
    ]
