# Generated by Django 6.1 on 2026-09-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_codesequence_last_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
    ]
