# Generated by Django 6.1 on 2026-09-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_product_product_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSequence',
        ),
    ]
