# Generated by Django 6.1 on 2026-09-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_protect_transaction_product_and_sync_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_leadership_restricted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='صنف قائد مقيد'),
        ),
        migrations.CreateModel(
            name='LeadershipAccessConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by_note', models.CharField(help_text='ملاحظة يدوية توثّق سبب/جهة منح الصلاحية', max_length=255)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadership_access', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الصلاحية')),
            ],
            options={
                'verbose_name': 'إعداد صلاحية القائد',
                'verbose_name_plural': 'إعدادات صلاحية القائد',
            },
        ),
        migrations.CreateModel(
            name='LeadershipAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_LIST', 'عرض قائمة أصناف القائد'), ('VIEW_DETAIL', 'عرض تفاصيل صنف'), ('CREATE', 'إضافة صنف'), ('UPDATE', 'تعديل صنف'), ('DELETE', 'حذف صنف (Soft)'), ('EXPORT', 'تصدير ملف Excel')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل وصول القائد',
                'verbose_name_plural': 'سجلات وصول القائد',
            },
        ),
    ]
