# Generated by Django 5.2.17 on 2026-09-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_v2_leader_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leadershipaccessconfig',
            options={'verbose_name': 'Leadership Access Config', 'verbose_name_plural': 'Leadership Access Configs'},
        ),
        migrations.AlterModelOptions(
            name='leadershipaccesslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='inventory_a_product_e9bec8_idx',
            old_name='inv_actlog_prod_date_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='inventory_i_product_2e3433_idx',
            old_name='inv_trans_prod_date_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('ADD', 'ADD'), ('EDIT', 'EDIT'), ('DELETE', 'DELETE'), ('IN', 'IN'), ('OUT', 'OUT'), ('ADJUST', 'ADJUST')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='new_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='old_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partner'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJUST', 'ADJUST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='leadershipaccessconfig',
            name='granted_by_note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leadershipaccessconfig',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadership_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadershipaccesslog',
            name='action',
            field=models.CharField(choices=[('VIEW_LIST', 'view list'), ('VIEW_DETAIL', 'view detail'), ('CREATE', 'create'), ('UPDATE', 'update'), ('DELETE', 'delete'), ('EXPORT', 'export'), ('TRANSACTION', 'transaction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_leader_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('SUPPLIER', 'supplier'), ('CLIENT', 'client'), ('OTHER', 'other')], default='CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_leadership_restricted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_leader_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
