# Generated by Django 5.2.17 on 2026-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_inventorytransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('ADD', 'إضافة'), ('EDIT', 'تعديل'), ('DELETE', 'حذف'), ('IN', 'استلام'), ('OUT', 'صرف'), ('ADJUST', 'تسوية')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'إستلام / وارد'), ('OUT', 'صرف / صادر'), ('ADJUST', 'تسوية / جرد')], max_length=10),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('SUPPLIER', 'مورد'), ('CLIENT', 'عميل'), ('OTHER', 'أخرى')], default='CLIENT', max_length=20),
        ),
    ]
