"""

Django settings for config project.



Generated by 'django-admin startproject' using Django 6.0.7.



For more information on this file, see

https://docs.djangoproject.com/en/6.0/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/6.0/ref/settings/

"""



import os

from pathlib import Path



from django.core.exceptions import ImproperlyConfigured



try:

    from dotenv import load_dotenv

    load_dotenv()

except ImportError:

    # python-dotenv is a dev convenience only. In production the real

    # process environment (systemd/Docker/etc.) already provides these

    # variables, so a missing package here is not an error.

    pass



# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent





def env_bool(name, default):

    value = os.environ.get(name)

    if value is None:

        return default

    return value.strip().lower() in ("1", "true", "yes", "on")





# SECURITY WARNING: keep the secret key used in production secret!

DEBUG = env_bool("DJANGO_DEBUG", True)



SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")



if not SECRET_KEY:

    if DEBUG:

        # Fine for local development only — never used when DEBUG=False.

        SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"

    else:

        raise ImproperlyConfigured(

            "DJANGO_SECRET_KEY environment variable is required when DEBUG=False."

        )



ALLOWED_HOSTS = [

    host.strip()

    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")

    if host.strip()

]



if DEBUG and not ALLOWED_HOSTS:

    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]



CSRF_TRUSTED_ORIGINS = [

    origin.strip()

    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")

    if origin.strip()

]





# Application definition



LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "dashboard"

LOGOUT_REDIRECT_URL = "login"



INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'django.contrib.humanize',

    'inventory',

]



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'inventory.middleware.CurrentUserMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'config.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.template.context_processors.i18n',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'inventory.context_processors.inventory_notifications',

            ],

        },

    },

]



WSGI_APPLICATION = 'config.wsgi.application'





# Database

# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#

# Defaults to SQLite for local development. Set DJANGO_DB_ENGINE=postgres

# (plus the DJANGO_DB_* variables below) to use PostgreSQL in production —

# recommended once more than one person uses the system at the same time,

# since SQLite does not handle concurrent writers well.



import dj_database_url



if os.environ.get("DATABASE_URL"):

    DATABASES = {

        'default': dj_database_url.config(

            default=os.environ.get("DATABASE_URL"),

            conn_max_age=600,

            conn_health_checks=True,

        )

    }

elif os.environ.get("DJANGO_DB_ENGINE") == "postgres":

    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.postgresql',

            'NAME': os.environ["DJANGO_DB_NAME"],

            'USER': os.environ["DJANGO_DB_USER"],

            'PASSWORD': os.environ["DJANGO_DB_PASSWORD"],

            'HOST': os.environ.get("DJANGO_DB_HOST", "localhost"),

            'PORT': os.environ.get("DJANGO_DB_PORT", "5432"),

        }

    }

else:

    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.sqlite3',

            'NAME': BASE_DIR / 'db.sqlite3',

        }

    }





# Password validation

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/6.0/topics/i18n/



LANGUAGE_CODE = 'en'



LANGUAGES = [

    ('en', 'English'),

    ('ar', 'العربية'),

]



LOCALE_PATHS = [BASE_DIR / 'locale']



TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Africa/Cairo")



USE_I18N = True



USE_TZ = True





# Static & media files

# https://docs.djangoproject.com/en/6.0/howto/static-files/



SITE_URL = os.environ.get("DJANGO_SITE_URL", "http://127.0.0.1:8000")



STATIC_URL = "static/"

STATICFILES_DIRS = [

    BASE_DIR / "static",

]

# Target directory for `collectstatic` in production. Not used in

# development (runserver serves STATICFILES_DIRS directly).

STATIC_ROOT = BASE_DIR / "staticfiles"



MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"





# Security hardening — only meaningful (and only enabled) once the site

# is actually served over HTTPS, i.e. DEBUG=False in a real deployment.

if not DEBUG:

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", True)

    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = "DENY"


# Auto-allow Render hosts
if os.environ.get('RENDER'):
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))

# Auto-allow Vercel hosts
if os.environ.get('VERCEL'):
    ALLOWED_HOSTS.append('.vercel.app')
